### ISSUE TITLE
Crash after opening picker

### ISSUE THREAD

**Issue by barredterra** [pinkfish/flutter_places_dialog#1]
I created a brand new flutter app with Kotlin support. I configured everything according to README. I'm using the `main.dart` from the example. App starts. When i klick on "Pick" it opens the picker for half a second, then crashes:

```
Launching lib/main.dart on MyDevice in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
Skipping compilation. Fingerprint match.
Built build/app/outputs/apk/debug/app-debug.apk (33.6MB).
I/FlutterActivityDelegate(22909): onResume setting current activity to this
I/flutter (22909): Initialized api key AIzaSyA5vzdfghjklö841236842SMhRYqo true
Syncing files to device MyDevice...
I/FlutterActivityDelegate(22909): onResume setting current activity to this
D/AppTracker(22909): App Event: start
I/vndksupport(22909): sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
E/        (22909): Cannot load libgui-plugin
I/flutter (22909): Opening places dialog
D/AppTracker(22909): App Event: stop
E/AndroidRuntime(22909): FATAL EXCEPTION: main
E/AndroidRuntime(22909): Process: com.example.flutterlocationdialog, PID: 22909
E/AndroidRuntime(22909): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=42, result=2, data=null} to activity {com.example.flutterlocationdialog/com.example.flutterlocationdialog.MainActivity}: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime(22909): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4528)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4571)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(22909): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1744)
E/AndroidRuntime(22909): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(22909): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.main(ActivityThread.java:6809)
E/AndroidRuntime(22909): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22909): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime(22909): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime(22909): Caused by: java.lang.NullPointerException: intent must not be null
E/AndroidRuntime(22909): 	at com.google.android.gms.common.internal.zzbq.checkNotNull(Unknown Source:8)
E/AndroidRuntime(22909): 	at com.google.android.gms.location.places.ui.zza.getStatus(Unknown Source:2)
E/AndroidRuntime(22909): 	at com.google.android.gms.location.places.ui.PlaceAutocomplete.getStatus(Unknown Source:0)
E/AndroidRuntime(22909): 	at com.example.flutterplacesdialog.FlutterPlacesDialogPlugin.onActivityResult(FlutterPlacesDialogPlugin.kt:98)
E/AndroidRuntime(22909): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:194)
E/AndroidRuntime(22909): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(22909): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:128)
E/AndroidRuntime(22909): 	at android.app.Activity.dispatchActivityResult(Activity.java:7267)
E/AndroidRuntime(22909): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4524)
E/AndroidRuntime(22909): 	... 9 more
D/AppTracker(22909): App Event: crash
```

Gradle: 4.4
SdkVersion: 27

**Comment by pinkfish** [comment]
Are you generating the api key correctly?  That was the big issue I had getting this working in the first place.  This error looks a little odd:
I/vndksupport(22909): sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
E/        (22909): Cannot load libgui-plugin

**Comment by pinkfish** [comment]
Also make sure you await the dialog, if it closes too early your activity
could go away which would cause this issue too.

**Comment by barredterra** [comment]
> Are you generating the api key correctly?
What do you mean? I'm using the API key for the Google Maps API from google's developer console.

> Also make sure you await the dialog
As i'm using the example file, (only changed the key) this should not be the problem

**Comment by pinkfish** [comment]
On iOS you need to set the key first via the API, the API does nothing on
android.  On android you need the google-services.json in your app
directory and the package name for you app must match in the services file
or it will fail.  This is the biggest way it kept dropping out for me :)

**Comment by barredterra** [comment]
I don't have the time to test the solution at the moment, so i close the issue for now.

**Comment by thanooshan** [comment]
App is crashing for me too.. any solutions..
